[package]
name = "geli-cli"
edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
geli-core = { path = "../geli-core/" }
